import type { Metadata } from 'next';
import 'typeface-red-hat-display'; // Importe a fonte Red Hat Display
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/></head>
      <body>{children}</body>
    </html>
  );
}
